apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo.fullname" . }}-config
data:
  odoo.conf: |
    [options]
    addons_path = /opt/odoo/src/odoo/addons,{{ .Values.gentian.modulesPath }}
    data_dir = /opt/odoo/data
    xmlrpc_port = {{ .Values.service.port }}
    workers = 0
    max_cron_threads = 1
    without_demo = all
  config.json: |
    {
      "tenantId": {{ .Values.tenantId | quote }},
      "moduleProfiles": []
    }
