{{- $gitSources := list -}}
{{- if .Values.gentian.gitSources -}}
  {{- $gitSources = .Values.gentian.gitSources -}}
{{- end -}}
{{- if and .Values.gentian.git.enabled (eq (len $gitSources) 0) -}}
  {{- $gitSources = list (dict "name" "default" "repo" .Values.gentian.git.repo "branch" .Values.gentian.git.branch "syncInterval" (int .Values.gentian.git.syncInterval) "secretName" .Values.gentian.git.secretName) -}}
{{- end -}}
{{- $addonsPaths := list "/opt/odoo/src/odoo/addons" "/opt/odoo/custom-addons" -}}
{{- range $gitSources -}}
  {{- $addonsPaths = append $addonsPaths (printf "%s/%s/current" $.Values.gentian.modulesPath .name) -}}
{{- end -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "odoo.fullname" . }}-config
data:
  odoo.conf: |
    [options]
    addons_path = {{ join "," $addonsPaths }}
    data_dir = /opt/odoo/data
    xmlrpc_port = {{ .Values.service.port }}
    workers = 0
    max_cron_threads = 1
    without_demo = all
    proxy_mode = True
  config.json: |
    {
      "tenantId": {{ .Values.tenantId | quote }},
      "moduleProfiles": []
    }
