apiVersion: v1
entries:
  activepieces:
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - kind: changed
          description: repository owner changed from fmjstudios to adnoctem
      artifacthub.io/images: |
        - name: activepieces
          image: docker.io/activepieces/activepieces:0.28.0
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Source
          url: https://github.com/adnoctem/helm
        - name: Support
          url: https://github.com/adnoctem/helm/issues
        - name: Activepieces Homepage
          url: https://www.activepieces.com/
        - name: Activepieces Documentation
          url: https://www.activepieces.com/docs/getting-started/introduction
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: 97DB36A8BD5E342076ED46D63E317D513290CC4B
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/97DB36A8BD5E342076ED46D63E317D513290CC4B
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.vendor: Ad Noctem Collective
    apiVersion: v2
    appVersion: 0.28.0
    created: "2026-07-14T09:44:28.903424798+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: ~15.5
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: ~19.5
    description: Activepieces is an open source all-in-one automation tool with 100+
      integrations
    digest: 7a8cfd5e0bb7e3f5904ec84ff9a1c499501ecc980e938c12c2398813f2a86e8f
    home: https://www.activepieces.com/
    icon: https://github.com/adnoctem/artwork/blob/425046029eaed451f5ced22ddc650059dff11878/projects/activepieces/icon/color/activepieces-icon-color.png
    keywords:
    - automation
    - workflow
    - activepieces
    - zapier
    - n8n
    kubeVersion: '>=1.26.0-0'
    maintainers:
    - email: info@adnoctem.co
      name: adnoctem
    - email: info@mvprowess.com
      name: MVProwess
    name: activepieces
    sources:
    - https://github.com/adnoctem/helm
    urls:
    - http://192.168.0.100:8089/activepieces-0.3.1.tgz
    version: 0.3.1
  - annotations:
      artifacthub.io/category: integration-delivery
      artifacthub.io/changes: |
        - kind: changed
          description: repository owner changed from fmjstudios to adnoctem
      artifacthub.io/images: |
        - name: activepieces
          image: docker.io/activepieces/activepieces:0.28.0
      artifacthub.io/license: MIT
      artifacthub.io/links: |
        - name: Source
          url: https://github.com/adnoctem/helm
        - name: Support
          url: https://github.com/adnoctem/helm/issues
        - name: Activepieces Homepage
          url: https://www.activepieces.com/
        - name: Activepieces Documentation
          url: https://www.activepieces.com/docs/getting-started/introduction
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: 97DB36A8BD5E342076ED46D63E317D513290CC4B
        url: https://keys.openpgp.org/vks/v1/by-fingerprint/97DB36A8BD5E342076ED46D63E317D513290CC4B
      org.opencontainers.image.licenses: MIT
      org.opencontainers.image.vendor: Ad Noctem Collective
    apiVersion: v2
    appVersion: 0.28.0
    created: "2026-07-14T09:44:28.894627225+02:00"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: oci://registry-1.docker.io/bitnamicharts
      version: ~15.5
    - condition: redis.enabled
      name: redis
      repository: oci://registry-1.docker.io/bitnamicharts
      version: ~19.5
    description: Activepieces is an open source all-in-one automation tool with 100+
      integrations
    digest: b7c3b3e83345840c31bfdf5dfc08fb4fc93fd6a932c1fa60d46ddf7356f7b2fa
    home: https://www.activepieces.com/
    icon: https://github.com/adnoctem/artwork/blob/425046029eaed451f5ced22ddc650059dff11878/projects/activepieces/icon/color/activepieces-icon-color.png
    keywords:
    - automation
    - workflow
    - activepieces
    - zapier
    - n8n
    kubeVersion: '>=1.26.0-0'
    maintainers:
    - email: info@adnoctem.co
      name: adnoctem
    - email: info@mvprowess.com
      name: MVProwess
    name: activepieces
    sources:
    - https://github.com/adnoctem/helm
    urls:
    - http://192.168.0.100:8089/activepieces-0.3.0.tgz
    version: 0.3.0
  odoo:
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.905786749+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: 87733a9025829f1cf8022cd6f457b64fa2e16bda4cd2fdd11cf5ffeeb35ce632
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.8.tgz
    version: 0.1.8
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.905621813+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: 42eb22d03b9921e7f310d7a05a3ff9f24db550e650a6614bf43f3631287c888e
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.7.tgz
    version: 0.1.7
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.905448005+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: ed4581b9b2058820dcc0a41d2bc95db9d617313b1b6ba347cc5916370916b787
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.6.tgz
    version: 0.1.6
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.905258662+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: 144953e3c1f0728f37b9567033fa3127df43c2a30da753b3ccf035febfe4f8c5
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.5.tgz
    version: 0.1.5
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.904997305+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: 1be1c7c0f4bbbbd282ee2b511f75157039522fb5265933b098d9b0a1608a6dab
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.4.tgz
    version: 0.1.4
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.904705037+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: 15cb7fcd5f5fa7993343607b311e0feeaadd3bf5fb32208ae747c453935af9fb
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.904098865+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: 5c9c6d9f99de072410e5533dce9cb1f2c369dc55ce31319c6b3da79056e385a1
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.903777143+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: c69d239c28e928ea852fbe311eaa2fd1c567ca5a00ed0c42dc88c7ef9713c575
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "19.0"
    created: "2026-07-14T09:44:28.903610746+02:00"
    description: Odoo Community (OCB) for Gentian OS tenants
    digest: b239e8d3dec61ea35de2415c7526a753c29cbb711dec66c0cfda0e290217be4b
    name: odoo
    type: application
    urls:
    - http://192.168.0.100:8089/odoo-0.1.0.tgz
    version: 0.1.0
generated: "2026-07-14T09:44:28.881937145+02:00"
