apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - profile.yaml
  - oidc-catalog.yaml
configMapGenerator:
  - name: nextcloud-suite-me-portal-bridge-sso
    namespace: crossplane-system
    files:
      - nextcloud-portal-sso.html=assets/nextcloud-portal-sso.html
generatorOptions:
  disableNameSuffixHash: true
  labels:
    gentianos.io/profile-name: nextcloud-suite-me
    gentianos.io/asset: portal-bridge-sso
    app.kubernetes.io/managed-by: gentian-os
