apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "gentian-app.fullname" . }}
  labels:
    {{- include "gentian-app.labels" . | nindent 4 }}
rules:
  - apiGroups: ["gentianos.io"]
    resources: ["tenants"]
    verbs: ["get", "patch"]
  - apiGroups: ["gentianos.io"]
    resources: ["appcatalogues", "appprofiles"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gentian-app.fullname" . }}
  labels:
    {{- include "gentian-app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "gentian-app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gentian-app.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "gentian-app.fullname" . }}
rules:
  - apiGroups: ["gentianos.io"]
    resources: ["apps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gentian-app.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "gentian-app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "gentian-app.fullname" . }}
