apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gentian-app.fullname" . }}-web
  labels:
    {{- include "gentian-app.web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gentian-app.name" . }}-web
  template:
    metadata:
      labels:
        {{- include "gentian-app.web.labels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "gentian-app.fullname" . }}-web-nginx
