apiVersion: gentianos.io/v1alpha1
kind: AppProfile
metadata:
  name: odoo-cb-accounting
  labels:
    gentianos.io/profile-name: odoo-cb-accounting
  annotations:
    gentianos.io/platform-app: "false"
    gentianos.io/deployment-role: module
    gentianos.io/requires-profile: odoo-cb-base
    gentianos.io/keycloak-group-attributes: '{"gentianOdooModules":["accounting"],"gentianOdooGroupRoles":["account.group_account_invoice"]}'
    gentianos.io/portal-auth-mode: oidc
spec:
  displayName: "Odoo Accounting"
  description: "Accounting and financial management module for Odoo."
  family: odoo
  catalogueVersion: "1.0.0"
  edition: standard
  trustTier: platform
  license: LGPL-3.0
  tile:
    icon: analytics

  portalTiles:
    - name: odoo-accounting
      displayName:
        en_US: "Odoo Accounting"
        de_DE: "Odoo Finanzen"
      linkSuffix: "/web?gentian_embed=1&action=account.open_account_journal_dashboard_kanban"
      linkTarget: embedded
      allowedGroup: "App Users"

  compositionRef: app-odoo
  deploymentMethod: crossplane
  chart:
    repository: http://192.168.0.100:8089
    name: odoo
    version: "0.1.3"
  extraValues:
    odoo:
      module: account
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
